/*
  This file is auto-generated by `pnpm run registerIntegrations`
  !!! Do not edit this file manually !!!
*/

import { IntegrationsType } from 'nocodb-sdk';
import type { IntegrationEntry } from '@noco-local-integrations/core';

export default [] as IntegrationEntry[];
